# ##############################################################################
#  Copyright (c) Matthieu Gallet <github@19pouces.net> 2023.                   #
#  This file constants.py is part of DiagralHomekit.                           #
#  Please check the LICENSE file for sharing or distribution permissions.      #
# ##############################################################################
"""Register API requests and responses."""
import json
from typing import Dict, List

from requests import Response

RESPONSES: Dict[str, List[Dict]] = {}


def request_mock(mock, endpoint, json_data=None, method="POST"):
    """Mock requests to the official API."""
    if endpoint not in RESPONSES:
        raise ValueError(f"Unknown endpoint {endpoint}.")
    for response in RESPONSES[endpoint]:
        if response.post_query == json_data:
            return response
    raise ValueError(f"Unknown json data for endpoint {endpoint}.")


def register(endpoint: str, response_data, json_data, status_code: int):
    """Register test data for a given endpoint."""
    response = Response()
    response._content = json.dumps(response_data).encode("utf-8")
    response.encoding = "utf-8"
    response.post_query = json_data
    response.status_code = status_code
    RESPONSES.setdefault(endpoint, [])
    RESPONSES[endpoint].append(response)


register(
    "/configuration/getSystems",
    {
        "diagralId": "28231076-0553-4add-a636-c1e0a20f139c",
        "systems": [
            {
                "name": "Home-2",
                "id": 129734,
                "role": 0,
                "installationComplete": True,
                "standalone": False,
            },
            {
                "name": "Home",
                "id": 81838,
                "role": 0,
                "installationComplete": True,
                "standalone": False,
            },
            {
                "name": "Home-3",
                "id": 914741,
                "role": 0,
                "installationComplete": True,
                "standalone": False,
            },
        ],
    },
    {},
    200,
)
register(
    "/authenticate/login",
    {"message": "error.connect.mydiagralusernotfound", "details": "Item not found"},
    {"username": "diagral@example.com", "password": "wrong"},
    404,
)
register(
    "/authenticate/login",
    {
        "sessionId": "eyJhbGciOiJFUzI1NiIsInR5cCI6Ik",
        "diagralId": "28231076-0553-4add-a636-c1e0a20f139c",
        "cryptedPassword": "crypted_password",
        "username": "diagral@example.com",
        "gender": "male",
        "firstName": "firstName",
        "lastName": "lastName",
        "mobile": None,
        "locale": None,
        "country": "FR",
        "postalCode": "75000",
        "city": "Paris",
        "address": "Paris",
        "newsletter": False,
        "partners": None,
        "acceptedCGU": False,
        "cguUrl": "https://appv3.tt-monitor.com/cgu/diagral/FR/index.html",
        "userType": "CUSTOMER",
        "expiresIn": 3600000,
    },
    {"username": "diagral@example.com", "password": "p4ssw0rD"},
    200,
)
register("/authenticate/logout", None, {"systemId": "null"}, 401)
register(
    "/authenticate/connect",
    {
        "message": "transmitter.connection.overlimit",
        "details": "Connection has reached the limit per hour",
    },
    {
        "masterCode": "8888",
        "transmitterId": "123456789ABCDE",
        "systemId": 81839,
        "role": 0,
    },
    500,
)
register(
    "/authenticate/connect",
    {
        "message": None,
        "ttmSessionId": "123456789abcdefdabb43a003094ea780",
        "systemState": "group",
        "groups": [1, 2, 3, 4],
        "groupList": [],
        "gprsConnection": None,
        "status": "OK",
        "versions": {
            "box": "1.1.13",
            "boxRadio": "11",
            "plugKnx": "1.1.10",
            "rawVersions": "V1.1.13",
        },
        "connectedUserType": "RESTRICTED",
        "codeIndex": 3,
        "userRightsConfiguration": None,
    },
    {
        "masterCode": "8888",
        "transmitterId": "123456789ABCDE",
        "systemId": 81838,
        "role": 0,
    },
    200,
)
register(
    "/configuration/getConfiguration",
    {
        "transmitterId": "123456789ABCDE",
        "centralId": "123456789ABCF0",
        "installationComplete": True,
        "name": "Home",
        "role": 0,
        "rights": {
            "UNIVERSE_ALARMS": "true",
            "UNIVERSE_OPENINGS": "true",
            "UNIVERSE_SCENARIOS": "true",
            "UNIVERSE_VIDEO": "true",
            "UNIVERSE_LIGHTS": "true",
        },
        "id": 81838,
        "standalone": False,
        "gprsPhone": None,
    },
    {"systemId": 81838, "role": 0},
    200,
)
register("/authenticate/logout", {"status": "OK"}, {"systemId": "null"}, 200)
register(
    "/action/stateCommand",
    {
        "message": None,
        "systemState": "tempogroup",
        "groups": [1, 2],
        "defaults": "010000",
        "commandStatus": "CMD_OK",
    },
    {
        "systemState": "group",
        "group": [1, 2],
        "currentGroup": [],
        "nbGroups": "4",
        "ttmSessionId": "123456789abcdefdabb43a003094ea780",
    },
    200,
)
register(
    "/action/stateCommand",
    {
        "message": None,
        "systemState": "off",
        "groups": [],
        "defaults": "010000",
        "commandStatus": "CMD_OK",
    },
    {
        "systemState": "off",
        "group": [],
        "currentGroup": [],
        "nbGroups": "4",
        "ttmSessionId": "123456789abcdefdabb43a003094ea780",
    },
    200,
)
register(
    "/status/getSystemState",
    {
        "message": None,
        "systemState": "group",
        "groups": [1, 2, 3, 4],
        "defaults": "010000",
        "commandStatus": "CMD_OK",
    },
    {
        "centralId": "123456789ABCF0",
        "ttmSessionId": "123456789abcdefdabb43a003094ea780",
    },
    200,
)
register(
    "/configuration/getCentralStatusZone",
    {
        "centralStatus": {
            "mainPowerSupplyAlert": False,
            "secondaryPowerSupplyAlert": False,
            "defaultMediaAlert": False,
            "autoprotectionMechanicalAlert": False,
            "autoprotectionWiredAlert": False,
            "radioAlert": False,
            "activeGroups": {
                "1": False,
                "2": False,
                "3": False,
                "4": False,
                "5": False,
                "6": False,
                "7": False,
                "8": False,
            },
            "sytemState": 15,
            "sytemStateText": "MARCHE GROUPE",
        },
        "commandsStatus": [
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "index": 1,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "index": 2,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "index": 3,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "index": 4,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "index": 5,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "index": 6,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "index": 7,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "index": 8,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "index": 9,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "index": 10,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "index": 11,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "index": 12,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "index": 13,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "index": 14,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "index": 15,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "index": 16,
            },
        ],
        "transmittersStatus": [
            {
                "mediaADSLAlert": False,
                "mediaGSMAlert": False,
                "mediaRTCAlert": False,
                "outOfOrderAlert": False,
                "mainPowerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "index": 1,
            },
            {
                "mediaADSLAlert": False,
                "mediaGSMAlert": False,
                "mediaRTCAlert": False,
                "outOfOrderAlert": False,
                "mainPowerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "index": 2,
            },
            {
                "mediaADSLAlert": False,
                "mediaGSMAlert": False,
                "mediaRTCAlert": False,
                "outOfOrderAlert": False,
                "mainPowerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "index": 3,
            },
        ],
        "sensorsStatus": [
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 12,
                "index": 1,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 10,
                "index": 2,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": True,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 12,
                "index": 3,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 4,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 5,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 6,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 7,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 8,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 9,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 10,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 11,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 12,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 13,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 14,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 15,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 16,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 17,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 18,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 19,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 20,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 21,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 22,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 23,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 24,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 25,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 26,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 27,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 28,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 29,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 30,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 31,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 32,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 33,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 34,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 35,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 36,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 37,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 38,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 39,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 40,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 41,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 42,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 43,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 44,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 45,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 46,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 47,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 48,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 49,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 50,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 51,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 52,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 53,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 54,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 55,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 56,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 57,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 58,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 59,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 60,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 61,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 62,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 63,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 64,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 65,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 66,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 67,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 68,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 69,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 70,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 71,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 72,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 73,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 74,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 75,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 76,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 77,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 78,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 79,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "sensorAlert": False,
                "loopAlert": False,
                "maskAlert": False,
                "ejected": False,
                "numberOfSupervisions": 0,
                "index": 80,
            },
        ],
        "alarmsStatus": [
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "index": 1,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "index": 2,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "index": 3,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "index": 4,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "index": 5,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "index": 6,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "index": 7,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "index": 8,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "index": 9,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "index": 10,
            },
        ],
        "transceiverStatus": [
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "index": 1,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "index": 2,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "index": 3,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "index": 4,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "index": 5,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "index": 6,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "index": 7,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "index": 8,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "index": 9,
            },
            {
                "powerSupplyAlert": False,
                "secondaryPowerSupplyAlert": False,
                "autoprotectionMechanicalAlert": False,
                "radioAlert": False,
                "index": 10,
            },
        ],
    },
    {
        "centralId": "123456789ABCF0",
        "transmitterId": "123456789ABCDE",
        "systemId": 81838,
        "ttmSessionId": "123456789abcdefdabb43a003094ea780",
    },
    200,
)
