name: Test {{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}
on:
  push:
    branches:
    - master
jobs:
  unittests:
    name: Unittests Python {% raw %}${{ matrix.python-version }}{% endraw %}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.11']
    env:
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: {% raw %}${{ matrix.python-version }}{% endraw %}
    - uses: actions/setup-node@v2
      with:
        node-version: '18'
        check-latest: true
    - run: python3 -m pip install -U pip pytest poetry
    - run: poetry install
    - run: pytest
